### ISSUE TITLE
npm run  pack， err？

### ISSUE THREAD

**Issue by wwb568109135** [paulbjensen/book-examples#7]
wuwanbing@WUWANBING MINGW64 /E/demo/cross-platform-desktop-applications/chapter-04/lorikeet-electron (master)
$ npm run pack

> lorikeet@1.0.0 pack E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron
> build

No native production dependencies
Packaging for win32 x64 using electron 1.8.8 to dist\win-unpacked
Warning: Application icon is not set, default Electron icon will be used
Unhandled rejection Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1148:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
From previous event:
    at E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\src\util\nodeHttpExecutor.ts:26:12
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at NodeHttpExecutor.download (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\out\util\nodeHttpExecutor.js:139:11)
    at download (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder-http\src\httpExecutor.ts:39:38)
    at E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder-util\src\binDownload.ts:49:3
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at doGetBin (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder-util\out\binDownload.js:54:21)
    at getBin (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder-util\src\binDownload.ts:23:38)
    at getBinFromBintray (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder-util\src\binDownload.ts:13:10)
    at Object.<anonymous> (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\src\targets\nsis.ts:23:25)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at targetClass (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\src\winPackager.ts:81:20)
    at WinPackager.createTargets (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\src\winPackager.ts:78:73)
    at createTargets (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\src\targets\targetFactory.ts:22:12)
    at E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\src\packager.ts:175:41
From previous event:
    at Packager.doBuild (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\out\packager.js:299:11)
    at E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\src\packager.ts:143:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\out\packager.js:251:11)
    at E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\src\builder.ts:214:40
    at Generator.next (<anonymous>)
From previous event:
    at build (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\out\builder.js:63:21)
    at Object.<anonymous> (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\out\cli\build-cli.js:68:41)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1148:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
From previous event:
    at E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\src\util\nodeHttpExecutor.ts:26:12
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at NodeHttpExecutor.download (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\out\util\nodeHttpExecutor.js:139:11)
    at download (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder-http\src\httpExecutor.ts:39:38)
    at E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder-util\src\binDownload.ts:49:3
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at doGetBin (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder-util\out\binDownload.js:54:21)
    at getBin (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder-util\src\binDownload.ts:23:38)
    at getBinFromBintray (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder-util\src\binDownload.ts:13:10)
    at getSignVendorPath (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\src\windowsCodeSign.ts:13:10)
    at E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\src\winPackager.ts:177:46
From previous event:
    at WinPackager.signAndEditResources (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\out\winPackager.js:233:11)
    at E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\src\winPackager.ts:190:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at WinPackager.postInitApp (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\out\winPackager.js:242:11)
    at E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\src\platformPackager.ts:203:148
From previous event:
    at WinPackager.doPack (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\out\platformPackager.js:262:11)
    at E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\src\platformPackager.ts:98:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\out\platformPackager.js:160:11)
    at E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\src\packager.ts:175:22
From previous event:
    at Packager.doBuild (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\out\packager.js:299:11)
    at E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\src\packager.ts:143:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\out\packager.js:251:11)
    at E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\src\builder.ts:214:40
    at Generator.next (<anonymous>)
From previous event:
    at build (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\out\builder.js:63:21)
    at Object.<anonymous> (E:\demo\cross-platform-desktop-applications\chapter-04\lorikeet-electron\node_modules\electron-builder\out\cli\build-cli.js:68:41)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! lorikeet@1.0.0 pack: `build`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the lorikeet@1.0.0 pack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wuwanbing\AppData\Roaming\npm-cache\_logs\2018-11-30T04_14_14_973Z-debug.log

wuwanbing@WUWANBING MINGW64 /E/demo/cross-platform-desktop-applications/chapter-04/lorikeet-electron (master)
$

**Comment by paulbjensen** [comment]
Hi,

What version of Windows, Node.js, and Electron do you have installed?

**Comment by wwb568109135** [comment]
window 7 

$ node -v
v8.12.0

$ npm -v
6.4.1

$ electron -v
v3.0.10

**Comment by paulbjensen** [comment]
I think I know what the issue is. The version of Electron that you've got there is much newer than the version of Electron I was using at the time of writing the book.

What I will do is try and replicate the issue that you are experiencing using that particular version of Windows, Node.js, NPM and Electron, and then see if I can get the code example to work with the latest version of Electron.

Paul

**Comment by wwb568109135** [comment]
thanks 
I'm trying to solve it myself.
